name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies with yarn
        run: yarn install --non-interactive --frozen-lockfile

      - name: Build for linux
        run: |
          rm -rf ./.github
          yarn run build

      - name: Create debian package
        run: yarn run build:deb

      - name: Publish deb package to bintray
        run: yarn run build:deb-publish
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Install Snapcraft with LXD
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
          use_lxd: true

      - name: Create snap package
        run: yarn run build:snap

      - name: Publish to snap store
        run: |
          sudo snap install review-tools
          yarn run build:snap-publish
