name: release-windows

on:
  push:
    tags:
      - '*'

jobs:
  release-windows:
    name: release-windows
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.18.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pack for Windows
        run: npm run pack:windows

      - name: Download inno-setup installer
        working-directory: ./windows
        run: curl.exe --max-time 30 --retry 3 -L -o ./innosetup.exe https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe

      - name: Install inno-setup silently
        working-directory: ./windows
        run: ./innosetup.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL

      - name: Create installer
        run: npm run build:windows

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          file_glob: true
