name: release-mac

on:
  push:
    tags:
      - '*'

jobs:
  release-mac:
    name: release-mac
    runs-on: macos-10.15
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.18.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Packing for mac
        run: |
          rm -rf ./.github
          pnpm run pack:mac

      - name: Create zip package
        run: pnpm run build:mac-zip

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          file_glob: true

