name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies with yarn
        run: yarn install --non-interactive --frozen-lockfile

      - name: Build for linux
        run: |
          rm -rf ./.github
          yarn run build

      - name: Create debian installer
        run: yarn run build:deb

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
