name: release-mac

on:
  push:
    tags:
      - '*'

jobs:
  release-mac:
    name: release-mac
    runs-on: macos-10.15
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies with yarn
        run: yarn install --non-interactive --frozen-lockfile

      - name: Pack for mac os
        run: |
          rm -rf ./.github
          rm -rf ./tests
          yarn run pack:mac

      - name: Create zip package
        run: yarn run build:mac-zip

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          file_glob: true

